### ISSUE TITLE
Nil pointer dereference with runtime.GOMAXPROCS more than 1

### ISSUE THREAD

**Issue by silviucm** [franela/goreq#103]
Hi Guys,

I set runtime.GOMAXPROCS(4) in a small program where I check dead links, and I got this when doing parallel requests using your library.
With GOMAXPROCS == 1 this problem does not occur.
(go version go1.4.2 linux/amd64)

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x447496]

goroutine 130 [running]:
github.com/franela/goreq.Request.Do(0xc20801ec60, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc20802a5c0, 0x3d, ...)
	/var/www/go/src/github.com/franela/goreq/goreq.go:368 +0xe26
main.processUrl(0xc20802a5c0, 0x3d, 0x83aab0)
	/var/www/go/src/publicis/linkcheck/main.go:151 +0x33a
created by main.processLinksFile
	/var/www/go/src/publicis/linkcheck/main.go:94 +0x616

The null pointer exception seems to derive from a nil res instance, after you perform 
res, err := client.Do(req) 

If I modify your part in goreq.go at line 367 or 368 (I think originally it was 367) and replace it with the condition below (to avoid a nil res) it will work, but I don't know enough specifics of your library at this point to comment further.

			if res != nil {
				response = &Response{res, resUri, &Body{reader: res.Body}, req}
			} else {
				response = &Response{res, resUri, nil, req}
			}

Regards
silviu

**Comment by marcosnils** [comment]
@silviucm  do you have the last version of the library?. Can you please provide a quick snippet that reproduces the problem?. Thx!.

**Comment by silviucm** [comment]
Hi @marcosnils - yes, I only found out about your library the day I reported the bug

I think it's inevitable that you get that error unless you check for res != nil.
When you call res, err := client.Do(req) at line 348 in goreq.go, it calls the http package client:
c.doFollowingRedirects(req, shouldRedirectGet)
If you look at http://golang.org/src/net/http/client.go at line 410,  there is a 
return nil, urlErr

So depending on the circumstances, if that thing ever gets triggered, your code will explode if it doesn't check for res != nil

Here is the Gist to test it, I'm afraid it's completely random, and the code only explodes on Linux.
https://gist.github.com/silviucm/9f8b755f8ecb514887d6

I cannot give you the full list of URLs (about 1500) as it's the property of my workplace, but I can tell you that it explodes randomly, probably for the reason I mentioned above. Here are three cases where it exploded.

About to panic for url: Get http://www.theglobeandmail.com/globe-investor/personal-finance/investing-calculators/rent-versus-buy/article1391093 
read tcp 206.248.168.171:80: use of closed network connection

About to panic for url: id=smsr.com.cw
Get https://play.google.com/store/apps/details?id=smsr.com.cw
net/http: request canceled while waiting for connection

About to panic for url: Get http://www.getrichslowly.org/blog/2009/07/08/learning-to-budget-with-the-jars-system/
read tcp 206.248.168.178:80: use of closed network connection

cheers,
silviu

**Comment by marcosnils** [comment]
@silviucm now I see the error. I haven't noticed that .Do() could return nil. 

Seems like your proposition fixes the issue, do you want to send a PR so we can merge?

Thanks again for your contribution!.

**Comment by silviucm** [comment]
Hopefully closed by 386c0ec - will revisit if other issues arise. Cheers !
