### ISSUE TITLE
How to set TLSClientConfig

### ISSUE THREAD

**Issue by tooooolong** [franela/goreq#105]
use  net/http package

I can use 
```
tr := &http.Transport{
    TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
}

client := &http.Client{Transport: tr}
```
to skip verify

so how to do use goreq.

thank you

**Comment by marcosnils** [comment]
@tooooolong you can do it this way:

goreq.Request{Insecure: true, Uri: "https://someinsecureurl.com"}.Do()

That should work

**Comment by tooooolong** [comment]
@marcosnils Yes, it works.  Thank you!
