### ISSUE TITLE
Issue with Body.FromJsonTo()

### ISSUE THREAD

**Issue by fyaconiello** [franela/goreq#115]
I can't figure out if this is an error, or if I'm doing it wrong.

When I run this code:

    type FreckleEntries []struct {
        ID int `json:"id"`
        Date string `json:"date"`
        User struct {
            ID int `json:"id"`
            Email string `json:"email"`
            FirstName string `json:"first_name"`
            LastName string `json:"last_name"`
            ProfileImageURL string `json:"profile_image_url"`
            URL string `json:"url"`
        } `json:"user"`
        Billable bool `json:"billable"`
        Minutes int `json:"minutes"`
        Description string `json:"description"`
        Project struct {
            ID int `json:"id"`
            Name string `json:"name"`
            BillingIncrement int `json:"billing_increment"`
            Enabled bool `json:"enabled"`
            Billable bool `json:"billable"`
            Color string `json:"color"`
            URL string `json:"url"`
        } `json:"project"`
        Tags []struct {
            ID int `json:"id"`
            Name string `json:"name"`
            Billable bool `json:"billable"`
            FormattedName string `json:"formatted_name"`
            URL string `json:"url"`
        } `json:"tags"`
        SourceURL string `json:"source_url"`
        InvoicedAt time.Time `json:"invoiced_at"`
        Invoice struct {
            ID int `json:"id"`
            Reference string `json:"reference"`
            InvoiceDate string `json:"invoice_date"`
            State string `json:"state"`
            TotalAmount float64 `json:"total_amount"`
            URL string `json:"url"`
        } `json:"invoice"`
        Import struct {
            ID int `json:"id"`
            URL string `json:"url"`
        } `json:"import"`
        ApprovedAt time.Time `json:"approved_at"`
        ApprovedBy struct {
            ID int `json:"id"`
            Email string `json:"email"`
            FirstName string `json:"first_name"`
            LastName string `json:"last_name"`
            ProfileImageURL string `json:"profile_image_url"`
            URL string `json:"url"`
        } `json:"approved_by"`
        URL string `json:"url"`
        CreatedAt time.Time `json:"created_at"`
        UpdatedAt time.Time `json:"updated_at"`
    }

    var entries FreckleEntries
    res.Body.FromJsonTo(&entries)

using this payload:

    [
      {
        "id": 1,
        "date": "2012-01-09",
        "user": {
          "id": 5538,
          "email": "john.test@test.com",
          "first_name": "John",
          "last_name": "Test",
          "profile_image_url": "https://api.letsfreckle.com/images/avatars/0000/0001/avatar.jpg",
          "url": "https://api.letsfreckle.com/v2/users/5538"
        },
        "billable": true,
        "minutes": 60,
        "description": "freckle",
        "project": {
          "id": 37396,
          "name": "Gear GmbH",
          "billing_increment": 10,
          "enabled": true,
          "billable": true,
          "color": "#ff9898",
          "url": "https://api.letsfreckle.com/v2/projects/37396"
        },
        "tags": [
          {
            "id": 249397,
            "name": "freckle",
            "billable": true,
            "formatted_name": "#freckle",
            "url": "https://api.letsfreckle.com/v2/tags/249397"
          }
        ],
        "source_url": "http://someapp.com/special/url/",
        "invoiced_at": "2012-01-10T08:33:29Z",
        "invoice": {
          "id": 12345678,
          "reference": "AA001",
          "invoice_date": "2013-07-09",
          "state": "unpaid",
          "total_amount": 189.33,
          "url": "https://api.letsfreckle.com/v2/invoices/12345678"
        },
        "import": {
          "id": 8910,
          "url": "https://api.letsfreckle.com/v2/imports/8910"
        },
        "approved_at": "2012-01-10T08:33:29Z",
        "approved_by": {
          "id": 5538,
          "email": "john.test@test.com",
          "first_name": "John",
          "last_name": "Test",
          "profile_image_url": "https://api.letsfreckle.com/images/avatars/0000/0001/avatar.jpg",
          "url": "https://api.letsfreckle.com/v2/users/5538"
        },
        "url": "https://api.letsfreckle.com/v2/entries/1711626",
        "created_at": "2012-01-09T08:33:29Z",
        "updated_at": "2012-01-09T08:33:29Z"
      },
      {
        "id": 2,
        "date": "2012-01-09",
        "user": {
          "id": 5538,
          "email": "john.test@test.com",
          "first_name": "John",
          "last_name": "Test",
          "profile_image_url": "https://api.letsfreckle.com/images/avatars/0000/0001/avatar.jpg",
          "url": "https://api.letsfreckle.com/v2/users/5538"
        },
        "billable": true,
        "minutes": 60,
        "description": "freckle",
        "project": {
          "id": 37396,
          "name": "Gear GmbH",
          "billing_increment": 10,
          "enabled": true,
          "billable": true,
          "color": "#ff9898",
          "url": "https://api.letsfreckle.com/v2/projects/37396"
        },
        "tags": [
          {
            "id": 249397,
            "name": "freckle",
            "billable": true,
            "formatted_name": "#freckle",
            "url": "https://api.letsfreckle.com/v2/tags/249397"
          }
        ],
        "source_url": "http://someapp.com/special/url/",
        "invoiced_at": "2012-01-10T08:33:29Z",
        "invoice": {
          "id": 12345678,
          "reference": "AA001",
          "invoice_date": "2013-07-09",
          "state": "unpaid",
          "total_amount": 189.33,
          "url": "https://api.letsfreckle.com/v2/invoices/12345678"
        },
        "import": {
          "id": 8910,
          "url": "https://api.letsfreckle.com/v2/imports/8910"
        },
        "approved_at": "2012-01-10T08:33:29Z",
        "approved_by": {
          "id": 5538,
          "email": "john.test@test.com",
          "first_name": "John",
          "last_name": "Test",
          "profile_image_url": "https://api.letsfreckle.com/images/avatars/0000/0001/avatar.jpg",
          "url": "https://api.letsfreckle.com/v2/users/5538"
        },
        "url": "https://api.letsfreckle.com/v2/entries/1711626",
        "created_at": "2012-01-09T08:33:29Z",
        "updated_at": "2012-01-09T08:33:29Z"
      }
    ]

I only get the first record in the resulting `entries` var.

**Comment by marcosnils** [comment]
@fyaconiello this works for me: 

```go
package main

import (
	"fmt"
	"net/http"
	"net/http/httptest"
	"time"

	"github.com/franela/goreq"
)

var payload = `
[
  {
    "id": 1,
    "date": "2012-01-09",
    "user": {
      "id": 5538,
      "email": "john.test@test.com",
      "first_name": "John",
      "last_name": "Test",
      "profile_image_url": "https://api.letsfreckle.com/images/avatars/0000/0001/avatar.jpg",
      "url": "https://api.letsfreckle.com/v2/users/5538"
    },
    "billable": true,
    "minutes": 60,
    "description": "freckle",
    "project": {
      "id": 37396,
      "name": "Gear GmbH",
      "billing_increment": 10,
      "enabled": true,
      "billable": true,
      "color": "#ff9898",
      "url": "https://api.letsfreckle.com/v2/projects/37396"
    },
    "tags": [
      {
        "id": 249397,
        "name": "freckle",
        "billable": true,
        "formatted_name": "#freckle",
        "url": "https://api.letsfreckle.com/v2/tags/249397"
      }
    ],
    "source_url": "http://someapp.com/special/url/",
    "invoiced_at": "2012-01-10T08:33:29Z",
    "invoice": {
      "id": 12345678,
      "reference": "AA001",
      "invoice_date": "2013-07-09",
      "state": "unpaid",
      "total_amount": 189.33,
      "url": "https://api.letsfreckle.com/v2/invoices/12345678"
    },
    "import": {
      "id": 8910,
      "url": "https://api.letsfreckle.com/v2/imports/8910"
    },
    "approved_at": "2012-01-10T08:33:29Z",
    "approved_by": {
      "id": 5538,
      "email": "john.test@test.com",
      "first_name": "John",
      "last_name": "Test",
      "profile_image_url": "https://api.letsfreckle.com/images/avatars/0000/0001/avatar.jpg",
      "url": "https://api.letsfreckle.com/v2/users/5538"
    },
    "url": "https://api.letsfreckle.com/v2/entries/1711626",
    "created_at": "2012-01-09T08:33:29Z",
    "updated_at": "2012-01-09T08:33:29Z"
  },
  {
    "id": 2,
    "date": "2012-01-09",
    "user": {
      "id": 5538,
      "email": "john.test@test.com",
      "first_name": "John",
      "last_name": "Test",
      "profile_image_url": "https://api.letsfreckle.com/images/avatars/0000/0001/avatar.jpg",
      "url": "https://api.letsfreckle.com/v2/users/5538"
    },
    "billable": true,
    "minutes": 60,
    "description": "freckle",
    "project": {
      "id": 37396,
      "name": "Gear GmbH",
      "billing_increment": 10,
      "enabled": true,
      "billable": true,
      "color": "#ff9898",
      "url": "https://api.letsfreckle.com/v2/projects/37396"
    },
    "tags": [
      {
        "id": 249397,
        "name": "freckle",
        "billable": true,
        "formatted_name": "#freckle",
        "url": "https://api.letsfreckle.com/v2/tags/249397"
      }
    ],
    "source_url": "http://someapp.com/special/url/",
    "invoiced_at": "2012-01-10T08:33:29Z",
    "invoice": {
      "id": 12345678,
      "reference": "AA001",
      "invoice_date": "2013-07-09",
      "state": "unpaid",
      "total_amount": 189.33,
      "url": "https://api.letsfreckle.com/v2/invoices/12345678"
    },
    "import": {
      "id": 8910,
      "url": "https://api.letsfreckle.com/v2/imports/8910"
    },
    "approved_at": "2012-01-10T08:33:29Z",
    "approved_by": {
      "id": 5538,
      "email": "john.test@test.com",
      "first_name": "John",
      "last_name": "Test",
      "profile_image_url": "https://api.letsfreckle.com/images/avatars/0000/0001/avatar.jpg",
      "url": "https://api.letsfreckle.com/v2/users/5538"
    },
    "url": "https://api.letsfreckle.com/v2/entries/1711626",
    "created_at": "2012-01-09T08:33:29Z",
    "updated_at": "2012-01-09T08:33:29Z"
  }
]
`

type FreckleEntries []struct {
	ID   int    `json:"id"`
	Date string `json:"date"`
	User struct {
		ID              int    `json:"id"`
		Email           string `json:"email"`
		FirstName       string `json:"first_name"`
		LastName        string `json:"last_name"`
		ProfileImageURL string `json:"profile_image_url"`
		URL             string `json:"url"`
	} `json:"user"`
	Billable    bool   `json:"billable"`
	Minutes     int    `json:"minutes"`
	Description string `json:"description"`
	Project     struct {
		ID               int    `json:"id"`
		Name             string `json:"name"`
		BillingIncrement int    `json:"billing_increment"`
		Enabled          bool   `json:"enabled"`
		Billable         bool   `json:"billable"`
		Color            string `json:"color"`
		URL              string `json:"url"`
	} `json:"project"`
	Tags []struct {
		ID            int    `json:"id"`
		Name          string `json:"name"`
		Billable      bool   `json:"billable"`
		FormattedName string `json:"formatted_name"`
		URL           string `json:"url"`
	} `json:"tags"`
	SourceURL  string    `json:"source_url"`
	InvoicedAt time.Time `json:"invoiced_at"`
	Invoice    struct {
		ID          int     `json:"id"`
		Reference   string  `json:"reference"`
		InvoiceDate string  `json:"invoice_date"`
		State       string  `json:"state"`
		TotalAmount float64 `json:"total_amount"`
		URL         string  `json:"url"`
	} `json:"invoice"`
	Import struct {
		ID  int    `json:"id"`
		URL string `json:"url"`
	} `json:"import"`
	ApprovedAt time.Time `json:"approved_at"`
	ApprovedBy struct {
		ID              int    `json:"id"`
		Email           string `json:"email"`
		FirstName       string `json:"first_name"`
		LastName        string `json:"last_name"`
		ProfileImageURL string `json:"profile_image_url"`
		URL             string `json:"url"`
	} `json:"approved_by"`
	URL       string    `json:"url"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func main() {

	entries := FreckleEntries{}
	ts := httptest.NewServer(http.HandlerFunc(func(rw http.ResponseWriter, r *http.Request) {
		rw.Write([]byte(payload))
	}))

	res, _ := goreq.Request{Uri: ts.URL}.Do()

	res.Body.FromJsonTo(&entries)
	fmt.Println(len(entries))
	fmt.Println("First entry: ", entries[0])
	fmt.Println()
	fmt.Println("Second entry: ", entries[1])

}
```

Have you tried updating your code?

**Comment by fyaconiello** [comment]
I'm a little embarrassed. I found my issue. The test JSON works just fine, the actual json is in places missing attributes. I changed my `FreckleEntries` struct to account for this and everything works perfectly. Also, if I had spent a little more time testing I would have noticed that the same error I was getting when using your library was also happening when I tried a vanilla json unmarshal.

**Comment by marcosnils** [comment]
:+1:
