### ISSUE TITLE
Connection pool

### ISSUE THREAD

**Issue by patrickdappollonio** [franela/goreq#118]
Hello,

I have a request-intensive application who is facing an open file descriptor problem [(see here for a related issue)](https://stackoverflow.com/questions/12952833/lookup-host-no-such-host-error-in-go). Every few tries, my server starts telling that there's an error saying that `no such host` exists. 

I know it should be the caller issue the one that should be limiting the amount of requests, but it could also be nice if `goreq` could implement a connection pool (pre-configurable) like other libraries uses, such as redis libs who are able to limit a maximum amount of connections to that database and reuse those who are left by the application.

Thoughts?

**Comment by marcosnils** [comment]
@patrickdappollonio golang reuses and caches http connections internally (https://golang.org/src/net/http/client.go?s=6009:6070#L26). We wouldn't like to add  another layer of complexity and overhead into this process. If you're running out of descriptors we'd recommend either: 

- Checking that you're not leaking connections (close bodies properly)
- Increase max open files as needed
- If the above doesn't work, implement your own pooling strategy which is fairly simple to do in go. 

I'm closing as this won't likely be implemented.
