### ISSUE TITLE
error read on closed response body

### ISSUE THREAD

**Issue by mostafadahab** [franela/goreq#119]
When I try to do normal get request this error message appears:
```
http: read on closed response body 
```
my code is:
```go
res, err := goreq.Request{Uri: "http://www.google.com"}.Do()
if err != nil {
	panic(err)
}
fmt.Println(res.Body.ToString())
```
i'm using go 1.51

**Comment by marcosnils** [comment]
@mostafadahab this is because that request returns a 302. If you print `res.StatusCode` you can check that. 

In order to work you need to specify the `MaxRedirects` parameter to the `Goreq` struct.

**Comment by lucaswxp** [comment]
@marcosnils This seems counter-intuitive, so I only have to close the body if the statusCode is in the range 300-399 ? Otherwise goreq will close for me?

There are also cases where a redirect might have a body.
