### ISSUE TITLE
Request Query Strings are normalized to small letters

### ISSUE THREAD

**Issue by NlightNFotis** [franela/goreq#120]
Hello,

I am using your library to make some simple requests. I am building a requests query string like in the documentation, like this:

``` go
type RequestItem struct {
	SecretKey  string
	AccessKey  string
	CustomerID string
}
```

I then proceed to initialize a struct variable, and construct a request as per the following code:

``` go
res, err := goreq.Request{
	Uri: RancherUri,
	QueryString: queryItem,
	ShowDebug: true,
}.Do()
```

The string it produces however is something along these lines:

``` sh
accesskey=<redacted>&customerid=a_random_string&secretkey=<redacted>
```

when I what I want instead is the following:

``` sh
accessKey=<redacted>&customerId=a_random_string&secretKey=<redacted>
```

(with every second word capitalized, due to the design of the API I am programming against atm).

I found out that it's not possible to do that (at least, I poked inside `goreq.go` and couldn't get it to work, no matter how much I poked around `parseParam` and co), and I resolved to constructing the query string by hand, like the following code:

``` go
s := []string{"secretKey", "=", ZecretKey, "&", "accessKey", "=", ZAccessKey, "&", "customerId", "=", "a_random_client"}
queryString := strings.Join(s, "")
final := []string{RancherURI, "?", queryString}
finalUri := strings.Join(final, "")
```

and then proceed to create a request using only the URI:

``` go
res, err := goreq.Request{
	Uri: finalUri,
	ShowDebug: true,
}.Do()
```
But I find my last way of doing things non-optimal. Is there a better way of doing the same thing? Is the behavior I described a bug, or the lib's design? Is there some better way you could see to work around it?

Thank you for your time and the effort to build this otherwise magnificent software.

**Comment by marcosnils** [comment]
@NlightNFotis have you tried using query tags?

https://github.com/franela/goreq#user-content-tags

**Comment by marcosnils** [comment]
Just tested it and it works with url tags. Please comment to reopen if something is not working for you.

**Comment by NlightNFotis** [comment]
Thank you, it works perfectly with query tags. 

I feel slightly embarrassed now, I don't know how I missed it. Thanks again.
