### ISSUE TITLE
failed to handle 302 redirect

### ISSUE THREAD

**Issue by oliveagle** [franela/goreq#72]
`http.Get` works without exception. but goreq always fail 

     res, err := goreq.Request{Uri: "http://page.1688.com/shtml/static/431246723.html"}.Do()

log

     2015/01/09 14:19:15 Get http://127.0.0.1/: Error redirecting. MaxRedirects reached

then

	res, err := goreq.Request{
		Method:       "GET",
		Uri:          "http://detail.1688.com/offer/431246723.html",
		MaxRedirects: 2,
	}.Do()

log:

    2015/01/09 14:25:29 Get http://127.0.0.1/: dial tcp 127.0.0.1:80: connection refused

**Comment by marcosnils** [comment]
@oliveagle I've just tried the second approach that you've used and it worked for me.  However I see something weird in your last log line. Seems like Goreq is trying somehow to connect to your local machine ( ? ), as you can see it's throwing an error trying to connect to 127.0.0.1. Do you have some sort of proxy or something that's intercepting http requests?

Here's my output:

```go

import (
	"fmt"

	"github.com/franela/goreq"
)

func main() {

	res, err := goreq.Request{Uri: "http://page.1688.com/shtml/static/431246723.html", MaxRedirects: 1}.Do()

	fmt.Println(res, err)

}
```

log: 
```
&{200 -1 0xc20803c7a0 map[Connection:[keep-alive] Server:[Apache/2.2.22 (Unix)] Vary:[Accept-Encoding] Content-Type:[text/html; charset=GBK] Content-Language:[cn] Age:[1517] X-Cache:[HIT from cm3-static-002] Date:[Fri, 09 Jan 2015 13:15:23 GMT]]} <nil>
```

**Comment by marcosnils** [comment]
You can also run `curl -sS -v -L http://page.1688.com/shtml/static/431246723.html -o /dev/null` (if you're using linux) and paste the output here to see what may be causing the error.

**Comment by marcosnils** [comment]
@oliveagle I've noticed something. The URL that you used in the second example is not the same as the first one. The first example shows `http://page.1688.com/shtml/static/431246723.html` and the second shows `http://detail.1688.com/offer/431246723.html`. 

If

**Comment by marcosnils** [comment]
@oliveagle I've found the problem. There are two things to notice here: 

1) The URL that you used in the first and second example it's not the same. If you use goreq with the url you used in the first example and set the MaxRedirect parameter, Goreq will return the answer correctly (as you can see in my previous answer). 

2) The URL that you used in your second example `http://detail.1688.com/offer/431246723.html` will redirect to you 127.0.0.1 if no UserAgent is supplied. You can verify this by the following curl: `curl -v -L -sS http://detail.1688.com/offer/431246723.html -o /dev/null -H "User-agent:"`

So, in order for the second URL to work with Goreq you need to make the request as follows: 

```go
package main

import (
	"fmt"

	"github.com/franela/goreq"
)

func main() {

	res, err := goreq.Request{
		Method:       "GET",
		Uri:          "http://detail.1688.com/offer/431246723.html",
		MaxRedirects: 2,
		UserAgent:    "myagent",
	}.Do()

	fmt.Println(res, err)
}
```

Please give it a try and post your results.

**Comment by oliveagle** [comment]
thx for your patience . it works. :

package main


```javascript
res, err := goreq.Request{
Method:       "GET",
Uri:          "http://detail.1688.com/offer/431246723.html",
MaxRedirects: 2,  
UserAgent:    "myagent", 
Timeout:   5000 * time.Millisecond,  // this is also important.
}.Do()
```

res: 

    &{200 -1 0xc2080305a0 map[Date:[Mon, 12 Jan 2015 03:34:53 GMT] Connection:[keep-alive] Content-Language:[cn] Age:[868] X-Cache:[HIT from cm10-static-008] Content-Type:[text/html; charset=GBK] Server:[Apache/2.2.22 (Unix)] Vary:[Accept-Encoding]]} <nil>

is there any default value for those params?

**Comment by oliveagle** [comment]
btw,  I found that `goreq.Response` doesn't have `Request` property as `http.Get` does.  If redirect happens, people don't have a chance to know which url finally respond.

**Comment by marcosnils** [comment]
@oliveagle Goreq response has the response header attributes, you could do response.Header["Location"] to know which Url finally answered.

**Comment by marcosnils** [comment]
@oliveagle. I've changed goreq so it uses the default golang http user agent when not specifying one. 

Yo should be able to do the request like this now
```go
res, err := goreq.Request{
Uri:          "http://detail.1688.com/offer/431246723.html",
MaxRedirects: 2,  
Timeout:   5000 * time.Millisecond,  // this is also important.
}.Do()
```

**Comment by oliveagle** [comment]
great. thx a lot
