### ISSUE TITLE
leaking CLOSE_WAIT

### ISSUE THREAD

**Issue by mdu4rt3** [franela/goreq#76]
I'm running into a weird problem where Goreq seems to leak CLOSE_WAIT sockets. If you do many of these inside a loop eventually you'll run into a OS error "too many open files". Any suggestions appreciated. Thanks.

Example - 

```golang
package main

import (
        "github.com/franela/goreq"
        "time"
)

func main() {

        type Item struct {
                Id   int
                Name string
        }

        goreq.SetConnectTimeout(500 * time.Millisecond)

        item := Item{Id: 1111, Name: "foobar"}

        goreq.Request{
                Method:  "POST",
                Uri:     "http://xxx.xxx.xxx.xxx",
                Body:    item,
                Timeout: 500 * time.Millisecond,
        }.Do()

        goreq.Request{
                Method:  "POST",
               Uri:     "http://xxx.xxx.xxx.xxx",
                Body:    item,
                Timeout: 500 * time.Millisecond,
        }.Do()

        goreq.Request{
                Method:  "POST",
                Uri:     "http://xxx.xxx.xxx.xxx",
                Body:    item,
                Timeout: 500 * time.Millisecond,
        }.Do()

        goreq.Request{
                Method:  "POST",
                Uri:     "http://xxx.xxx.xxx.xxx",
                Body:    item,
                Timeout: 500 * time.Millisecond,
        }.Do()

        time.Sleep(1000000 * time.Millisecond)

}
```

As the process is running we check how many CLOSE_WAIT are opened. We see one for each request made. These will stick around as long as the process is running. 

lsof -p 31922 | grep CLOSE_WAIT

test2   31922 scanner    3u  IPv4 9394858      0t0     TCP localhost:40026->xxx.xxx.xxx.xxx:http (CLOSE_WAIT)
test2   31922 scanner    4u  0000     0,9        0    6269 anon_inode
test2   31922 scanner    5u  IPv4 9397699      0t0     TCP localhost:40027->xxx.xxx.xxx.xxx:http (CLOSE_WAIT)
test2   31922 scanner    6u  IPv4 9397700      0t0     TCP localhost:40028->xxx.xxx.xxx.xxx:http (CLOSE_WAIT)
test2   31922 scanner    7u  IPv4 9397701      0t0     TCP localhost:40029->xxx.xxx.xxx.xxx:http (CLOSE_WAIT)

**Comment by xetorthio** [comment]
Are you sure this is a goreq thing?  Did you try using native golang http requests and check if the same happens?

**Comment by mdu4rt3** [comment]
Hey, Thanks for the suggestion. I did some experiments and I've confirmed with the native golang http request this doesn't happen as long as you call resp.Body.Close() after using it. Otherwise yes it will leak CLOSE_WAIT. I will convert my code over to native golang http request for now. 

Thanks!

**Comment by marcosnils** [comment]
@mdu4rt3 sorry I couldn't reply earlier. The same thing is happening with `goreq`. Have you also tried issuing a  resp.Body.Close() in goreq's response?

**Comment by mdu4rt3** [comment]
I've confirmed that calling resp.Body.Close() on the goreq's response solves this issue. Thanks!

**Comment by marcosnils** [comment]
Nice!. Can you please close the issue?.

Thx!.
