### ISSUE TITLE
Cookies support

### ISSUE THREAD

**Issue by bfontaine** [franela/goreq#77]
Hello,

Would it be possible to add support for Cookies in `goreq`? Go 1.1 [introduced a cookiejar implementation](http://stackoverflow.com/a/19386573/735926), the jar has to be passed to the underlying `http.Client` and it just works™.

Thanks.

**Comment by marcosnils** [comment]
@bfontaine of course we can implement that. Would you suggest any API in particular to support it?

I'll try to craft something this weekend.

**Comment by bfontaine** [comment]
Thanks for the quick response. `http.Client` supports a `Jar` attribute for a cookies jar ([see the docs here](http://golang.org/pkg/net/http/#Client)). You’d just need to get an optional `Jar` attribute for a request and pass it to the client.

That would give us an API like:

```go
import (
    "net/http/cookiejar"
    "github.com/franela/goreq"
)

// create the cookie jar once
cookieJar, _ := cookiejar.New(nil)

// pass it to each request
res, _ := goreq.Request{
    Uri: "http://www.example.com",
    Jar: &cookieJar,
}
```

I guess it would be enough. The jar is then passed to the `http.Client`, which is now able to modify it. What do you think?

**Comment by marcosnils** [comment]
@bfontaine looks the simplest and fastest way to implement that so it can be definitely that. If you're currently needing the cookie feature right away you can always contribute and open a PR so I can merge. 

I was also thinking that we can add a `AddCookie` method to the request struct so goreq users won't even need to create the cookie jar or anything. What's your opinion about it?

**Comment by bfontaine** [comment]
> I was also thinking that we can add a `AddCookie` method to the request struct so goreq users won't even need to create the cookie jar or anything. What's your opinion about it?

Good idea. I just looked [at the docs](http://golang.org/pkg/net/http/cookiejar/) and the default `cookiejar` implementation doesn’t support a method like this. It only allows us to get *all* cookies and set *all* cookies. We need to collect all cookies added by `AddCookie` and pass them to the jar.

> If you're currently needing the cookie feature right away you can always contribute and open a PR so I can merge.

I implemented a quick&dirty solution in the meantime but I’ll give a try!

**Comment by bfontaine** [comment]
Is there something I need to do to have the test suite pass? It fails on the timeout part:

```
      Connection timeouts
        1) Should connect timeout after a default of 1000 ms
        2) Should connect timeout after a custom amount of time
        3) Should connect timeout after a custom amount of time even with method set

[…]

 59 tests complete (670 ms)
 3 tests failed:

  1) Connection timeouts Should connect timeout after a default of 1000 ms:

    Expected
    <time.Duration>: 23719930
to be >=
    <time.Duration>: 1000000000
[…]
```

**Comment by marcosnils** [comment]
@bfontaine do tests fail always for you?. Try sending the PR and let's see if travis also complains about that?

**Comment by bfontaine** [comment]
@marcosnils Yes these 3 tests always fail. I’ll open a PR when I’ll have a working code. I added a `Jar` attribute to the request and I’m currently struggling with a failing test where Go can’t parse my cookie.

I added this code in the responses:

```go
if r.Method == "GET" && r.URL.Path == "/setcookies" {
	defer r.Body.Close()
	w.Header().Add("Set-Cookie", "foobar=\"42x\"; Path=/setcookies")
	w.WriteHeader(200)
}
```

And this test:

```go
g.It("Should populate the cookiejar", func() {
	uri, err := url.Parse(ts.URL + "/setcookies")
	Expect(err).Should(BeNil())

	jar, _ := cookiejar.New(nil)
	Expect(err).Should(BeNil())

	res, err := Request{
		Uri: ts.URL + "/setcookies",
		Jar: jar,
	}.Do()

	Expect(err).Should(BeNil())
	Expect(res.Header.Get("Set-Cookie")).Should(Equal("foobar=\"42x\"; Path=/setcookies"))

	cookies := jar.Cookies(uri)
	Expect(len(cookies)).Should(Equal(1))

	cookie := cookies[0]
	Expect(*cookie).Should(Equal(http.Cookie{
		Name:  "foobar",
		Value: "42x",
		Path:  "/setcookies",
	}))
})
```

Go parses my cookie but not its path. It says it expected this:

```
    <http.Cookie>: {
        Name: "foobar",
        Value: "42x",
        Path: "",
        Domain: "",
        Expires: {sec: 0, nsec: 0, loc: nil},
        RawExpires: "",
        MaxAge: 0,
        Secure: false,
        HttpOnly: false,
        Raw: "",
        Unparsed: nil,
    }
```

to be equal to:

```
    <http.Cookie>: {
        Name: "foobar",
        Value: "42x",
        Path: "/setcookies",
        Domain: "",
        Expires: {sec: 0, nsec: 0, loc: nil},
        RawExpires: "",
        MaxAge: 0,
        Secure: false,
        HttpOnly: false,
        Raw: "",
        Unparsed: nil,
    }
```

I’m currently digging in the [RFC 2109](https://www.ietf.org/rfc/rfc2109.txt) and the [Go source code](https://golang.org/src/net/http/cookie.go) to understand why it doesn’t parse my path.

**Comment by marcosnils** [comment]
@bfontaine I've went into Go sourcecode and it seems that it does the Path, Expiration and some other fields validations internally. The only thing that you is the cookie name and the value when parsing using the jar.Cookies function. I believe we can remove the Path validation in the tests and it we should be ok.

Comments?

**Comment by marcosnils** [comment]
Also, how about changing the parameter Jar to CookieJar. I know it might be too much but reading "Jar" only it feels like weird for a first time user right?

**Comment by bfontaine** [comment]
Thanks for the feedback, I removed the Path validation and changed the parameter to CookieJar.
