### ISSUE TITLE
Unexpected "<nil>" at the end of JSON response

### ISSUE THREAD

**Issue by jimzhan** [franela/goreq#80]
As titled, we found this when testing on our internal server while other libraries (like gorequest) works.

```JSON
{"href":"https://api.example.com/v1/servers/mm8k7dAtvhC7nxAvIma238M1","name":"shadow","key":"shadow"} <nil>
```

**Comment by marcosnils** [comment]
@jimzhan I asumed that this wasn't wasn't a goreq error in the end. Right?
