### ISSUE TITLE
Goreq *should* send empty structfields in query string

### ISSUE THREAD

**Issue by bfontaine** [franela/goreq#83]
21edc82b prevents sending empty structfields in query string, but an empty field and no field is not the same. I’m working on a project where we have to deal with an API for which we need a text field. It’s empty most of the time, so our API call look like:

    GET /the/api?foo=2&bar=3&desc=

The `desc` param above is an empty string, but that’s not the same as the following query:

    GET /the/api?foo=2&bar=3

The first one says “here’s my `desc` param and it’s empty” and the second is “I don’t send you my `desc` param”. In our case the remote server give us an error saying a parameter is missing.

**Comment by marcosnils** [comment]
@bfontaine you're right. I haven't thought about that and I rushed to include 21edc82. I'll revert and we'll see how we can deal with 21edc82 was supposed to achieve. 

Thanks!.

**Comment by marcosnils** [comment]
Closed by 8b74f8a1a817ff67653a17b1b3d450efb8937437

**Comment by marcosnils** [comment]
@bfontaine I've decided to use tag options to customize this feature. That way we can still address the issue you've detected and we offer the possibility to ignore empty fields alternatively.

You can check the commit here: be149fea9861ab2af7e72f1bd6eb21135e7c7319

Thanks!

**Comment by bfontaine** [comment]
Thanks!
