### ISSUE TITLE
Access response cookies

### ISSUE THREAD

**Issue by vitalyisaev2** [franela/goreq#90]
Hello again. Currently I'm attempting to dive deeper in golang network programming and I would like to continue the use of your library. Now I'm stuck on getting the Cookies from the `Response` struct (I believe that standard ```http.Response``` lies somewhere beneath it).

```golang
	res, err := goreq.Request{
		Method: "POST",
		Uri:    *restAPI,
		Body:   providersRequest,
	}.Do()
        
       // This will give me a string, but I need http.Cookie
       cookieString := res.Header.Get("set-cookie")

       // This wil not compile
       cookieStruct := res.Cookies()
```
Thank you in advance!

**Comment by marcosnils** [comment]
@vitalyisaev2 you can get the raw `http.Response` and get the cookies from there. Here's the doc:
https://github.com/luin/ioredis/blob/master/test/unit/command.js

**Comment by vitalyisaev2** [comment]
Sorry but I cannot see anything but Javascript code there. Is the link
correct?
28.04.2015 22:10 пользователь "Marcos Nils" <notifications@github.com>
написал:

**Comment by marcosnils** [comment]
I've updated the link in the github issue :).

**Comment by vitalyisaev2** [comment]
Thank you!

**Comment by vitalyisaev2** [comment]
@marcosnils 
Unfortunately I rushed to conclusions... This code can't be compiled:

```golang
	providersRequest := JSONRPCRequest{
		Id:      "1",
		Jsonrpc: "2.0",
		Method:  "session_create_by_foreign_user",
		Params:  *params}

	fmt.Println("Request: %v\n", providersRequest)

	res, err := goreq.Request{
		Method: "POST",
		Uri:    *restAPI,
		Body:   providersRequest,
	}.Do()

	if err != nil {
		panic(err.Error())
	}

	fmt.Println(res.Response, err)
```

```bash
isaev@wks-isaev:~/prog/session/deploy/webserver2$ go run main.go 
# command-line-arguments
./main.go:87: res.Response undefined (type *goreq.Response has no field or method Response)
```
I'm on Ubuntu 14.10:
```bash
$ go version
go version go1.2.1 linux/amd64
```

**Comment by vitalyisaev2** [comment]
Updated to ```1.4.2```, now all works fine :)
