### ISSUE TITLE
how to work with session, while some url link have to login first before get

### ISSUE THREAD

**Issue by ghiewa** [franela/goreq#96]
as title, how, or is there any plan add this into project.

**Comment by marcosnils** [comment]
@ghiewa Goreq is an HTTP request library. As you know, HTTP is stateless so it doesn't make sense to have something like a `session` between different requests. `Session` is a concept of web server to maintain the state within the same user. 

If you want to perform a `login` and make consequent requests you'll have to do it in to steps:

1. Make a request to login (without redirect) and obtain the cookies from the response header (set-cookie)
2. Make further requests using the goreq AddCookie option and RedirectHeaders: true. If a redirect occurs then goreq will forward the specified cookie correctly to the destination URL.
