### ISSUE TITLE
Export Error.Timeout for cleaner code

### ISSUE THREAD

**Issue by rexposadas** [franela/goreq#98]
See: https://github.com/Stotz-Equipment/goreq/commit/94bbc8ac607112560b7e82b9dc1b0b09885d2bb7

I don't see the benefit of making `timeout` a private variable in the `Error` struct.   We can simplify the code by exporting Timeout and removing the getter method `Timeout()`

I also modified the grouping of variables per what is being done in the golang project: https://github.com/golang/go/blob/master/src/bufio/bufio.go#L21-26  but I don't how strictly they adhere to that coding style.

**Comment by marcosnils** [comment]
@rexposadas we made it that way to comply with the network Error interface http://golang.org/src/net/net.go#L207. In the future if we implement the Temporary function as well goreq errors can be type asserted against net.Error interface.

This won't likely change as it breaks backwards compatibility and It's idiomatic Go.

**Comment by rexposadas** [comment]
Thanks @marcosnils , i wasn't aware of plans to add the `Temporary()` func as well.
