### ISSUE TITLE
remove else for cleaner code

### ISSUE THREAD

**Issue by rexposadas** [franela/goreq#99]
I removed an unnecessary `else` block for cleaner code: https://github.com/Stotz-Equipment/goreq/commit/c81fc446a08c3568ae467b19e927fd53ecbcf77d

It's a small change. I can understand if you don't want it.  but, If you want it, I can create a PR.

**Comment by marcosnils** [comment]
@rexposadas sure, send a PR and I'll be glad to merge.

**Comment by marcosnils** [comment]
closed by #100
